
#Configurations related to materials.
[materials]
	#Should the mod find ingot materials with ores.
	ingot = true
	#Should the mod find gem materials with ores.
	gem = true
	#Should the mod find crystal materials with ores.
	crystal = true
	#Should the mod find dust materials with ores.
	dust = true
	#Should the mod find ingot materials without ores.
	ingotPlain = true
	#Should the mod find gem materials without ores.
	gemPlain = true
	#Should the mod find crystal materials without ores.
	crystalPlain = false
	#Should the mod find dust materials without ores.
	dustPlain = false
	#Should the mod not find materials with ores with used prefixes.
	nonPlainUsedPrefix = false
	#Should the mod not find materials with used prefixes when the material name is not found yet.
	strictUsedPrefix = false

#Configurations related to material overrides.
[materialOverrides]
	#List of materials that should be gems.
	gem = ["Coal", "Diamond", "Emerald", "Lapis", "Prismarine", "Quartz"]
	#List of materials that should be crystals.
	crystal = []
	#List of materials that should be dusts.
	dust = ["Redstone"]

#Configurations related to item selection.
[itemSelection]
	#List of mods that are preferred when selecting items in recipes.
	preferredMods = ["minecraft", "tconstruct", "tconevo", "draconicevolution", "taiga", "avaritia", "avaritiatweaks", "thermalfoundation", "thermalexpansion", "moretcon", "naturesaura", "immersiveengineering", "astralsorcery", "thaumcraft", "biomesoplenty", "iceandfire", "mekanism", "endreborn", "plustic", "divinerpg", "journey", "plustic", "botania", "twilightforest", "extrabotany", "botanicadds", "naturapledge", "theaurorian", "appliedenergistics2", "enderio", "endreborn", "quark", "nyx", "mysticalagriculture", "mysticalagradditions", "abyssalcraft", "acintegration", "gct_ores", "gct_mobs", "gct_tcon", "gct_aby", "mist", "blue_skies", "thebetweenlands", "extendedcrafting", "tiths", "nuclearcraft", "galacticraftcore", "additions", "contenttweaker", "jaopca"]

#Configurations related to the ore dictionary.
[oredict]
	#List of oredict names that should not be added.
	blacklist = []
	#List of oredict modules that should not be registered.
	moduleBlacklist = ["abyssalcraft_crystal_cluster", "abyssalcraft_crystal", "abyssalcraft_crystal_shard", "abyssalcraft_crystal_fragment"]
	#List of custom oredict entries to add. Format: <mod:item@meta=oredict>
	custom = ["gct_mobs:elementium_ore=oreElvenElementium", "divinerpg:arlemite_ore=oreArlemite", "additions:greedycraft-chloroplast_ore=oreChloroplast", "journey:flairiumore=oreFlairium", "journey:shadiumore=oreShadium", "blue_skies:ventium_ore=oreVentium", "blue_skies:horizonite_ore=oreHorizonite", "gct_aby:ethauxiumore=oreEthaxium", "divinerpg:rupee_ore=oreRupee", "journey:koriteore=oreKorite", "theaurorian:moonstoneore=oreMoonstone", "tiths:ore_polarium=orePolarium", "tiths:ore_hothium=oreHothium", "gct_mobs:orichalcos_ore=oreOrichalcos", "journey:orbaditeore=oreOrbadite", "gct_aby:yogsothothium_ore=oreYogsothothium", "tiths:ore_tonium=oreTonium", "journey:mekyumore=oreMekyum", "divinerpg:realmite_ore=oreRealmite", "journey:storonore=oreStoron", "gct_aby:shubniggurathium_ore=oreShubniggurathium", "theaurorian:ceruleanore=oreCerulean", "gct_mobs:terrasteel_ore=oreTerrasteel", "additions:taigaddon-immersed_silver_ore=oreSilverImmersed", "journey:celestiumore=oreCelestium", "gct_aby:nyarlathotepium_ore=oreNyarlathotepium", "tiths:ore_halleium=oreHalleium", "journey:hellstoneore=oreBloodcrust", "gct_aby:azathothium_ore=oreAzathothium", "tiths:ore_altairium=oreAltairium", "tiths:ore_stellarium=oreStellarium", "blue_skies:falsite_ore=oreFalsite", "gct_aby:dreadiumore=oreDreadium", "divinerpg:netherite_ore=oreLavaSolid", "journey:luniumore=oreLunium", "journey:desore=oreDes", "endreborn:block_wolframium_ore=oreWolframium", "botania:manaresource:7=ingotElvenElementium", "divinerpg:arlemite_ingot=ingotArlemite", "tiths:ingot_chloroplast=ingotChloroplast", "blue_skies:horizonite_ingot=ingotHorizonite", "journey:shadiumingot=ingotShadium", "blue_skies:ventium_ingot=ingotVentium", "journey:flairiumingot=ingotFlairium", "abyssalcraft:ethaxiumingot=ingotEthaxium", "divinerpg:rupee_ingot=ingotRupee", "journey:koriteingot=ingotKorite", "theaurorian:moonstoneingot=ingotMoonstone", "tiths:ingot_polarium=ingotPolarium", "tiths:ingot_hothium=ingotHothium", "extrabotany:material:1=ingotOrichalcos", "journey:orbaditeingot=ingotOrbadite", "gct_mobs:yogsothothium_ingot=ingotYogsothothium", "tiths:ingot_tonium=ingotTonium", "journey:mekyumingot=ingotMekyum", "divinerpg:realmite_ingot=ingotRealmite", "journey:storoningot=ingotStoron", "gct_mobs:shubniggurathium_ingot=ingotShubniggurathium", "theaurorian:ceruleaningot=ingotCerulean", "botania:manaresource:4=ingotTerrasteel", "tiths:ingot_immersed_silver=ingotSilverImmersed", "journey:celestiumingot=ingotCelestium", "gct_mobs:nyarlathotepium_ingot=ingotNyarlathotepium", "tiths:ingot_halleium=ingotHalleium", "journey:hellstoneingot=ingotBloodcrust", "gct_mobs:azathothium_ingot=ingotAzathothium", "tiths:ingot_altairium=ingotAltairium", "tiths:ingot_stellarium=ingotStellarium", "blue_skies:falsite_ingot=ingotFalsite", "abyssalcraft:dreadiumingot=ingotDreadium", "divinerpg:netherite_ingot=ingotLavaSolid", "journey:luniumingot=ingotLunium", "endreborn:item_ingot_wolframium=ingotWolframium", "journey:desingot=ingotDes"]

#Configurations related to recipes.
[recipes]
	#List of recipes that should not be added.
	blacklist = []
	#List of recipes by regex that should not be added.
	regexBlacklist = []

#Configurations related to color generation.
[colors]
	#The gamma value used to blend colors.
	gammaValue = 2.0
	#Should colors of all materials be reset on next startup.
	resetColors = false

#Configurations related to material localization.
[materialLocalization]
	#Should the mod check for material localization updates.
	checkL10nUpdates = false
	#The update interval of localization files in days.
	updateInterval = 3.0

