
[general]
	#The material blacklist of this module.
	materialBlacklist = []
	#The materials to force generate passive forms for this module.
	passiveMaterialWhitelist = ["ZirconiumMolybdenum", "Aurorianite", "Crystalline", "Umbra", "RoseGold", "Finallium", "Wavite", "Heavyalloy"]

